try:
    raise Exception("failed")
    print("")
except:
    ...    